version: "3.6"

services:
  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    volumes:
      - etcd_data:/bitnami/etcd

  indexer_sales:
    image: quay.io/apibara/sink-mongo:0.4.4
    depends_on:
      - etcd
    restart: always
    ports:
      - "8001:8001"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/sales.ts
      - --status-server-address=0.0.0.0:8001
      - --max-message-size=1GB
      - --timeout-duration-seconds=1200
    volumes:
      - ./indexer:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: sales-indexer
      AUTH_TOKEN: dna_xxx

  indexer_tax_txs:
    image: quay.io/apibara/sink-mongo:0.4.4
    depends_on:
      - etcd
    restart: always
    ports:
      - "8002:8002"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/tax_txs.ts
      - --status-server-address=0.0.0.0:8002
      - --max-message-size=1GB
      - --timeout-duration-seconds=1200
    volumes:
      - ./indexer:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: tax-txs-indexer
      AUTH_TOKEN: dna_xxx

  indexer_auto_renew:
    image: quay.io/apibara/sink-mongo:0.4.4
    depends_on:
      - etcd
    restart: always
    ports:
      - "8003:8003"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/auto_renew_updates.ts
      - --status-server-address=0.0.0.0:8003
      - --max-message-size=1GB
      - --timeout-duration-seconds=1200
    volumes:
      - ./indexer:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: auto-renew-updates-indexer
      AUTH_TOKEN: dna_xxx

  # sale_actions:
  #   container_name: sale_actions
  #   build:
  #     context: ./sale_actions/
  #     dockerfile: Dockerfile
  #   restart: always

  api_endpoint:
    container_name: api_endpoint
    build:
      context: ./api_endpoint/
      dockerfile: Dockerfile
    restart: always

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: "api.sales.starknet.id"
      SITES: "api.sales.starknet.id=api_endpoint:8080"

volumes:
  etcd_data:
  ssl_data:
